export const statesArray = [
  { name: "Киевская", value: 10 },
  { name: "Винницкая", value: 1 },
  { name: "Волынская", value: 18 },
  { name: "Днепропетровская", value: 11 },
  { name: "Донецкая", value: 13 },
  { name: "Житомирская", value: 2 },
  { name: "Закарпатская", value: 22 },
  { name: "Запорожская", value: 14 },
  { name: "Ивано-Франковская", value: 15 },
  { name: "Кировоградская", value: 16 },
  { name: "Луганская", value: 17 },
  { name: "Львовская", value: 5 },
  { name: "Николаевская", value: 19 },
  { name: "Одесская", value: 12 },
  { name: "Полтавская", value: 20 },
  { name: "Ровенская", value: 9 },
  { name: "Сумская", value: 8 },
  { name: "Тернопольская", value: 3 },
  { name: "Харьковская", value: 7 },
  { name: "Херсонская", value: 23 },
  { name: "Хмельницкая", value: 4 },
  { name: "Черкасская", value: 24 },
  { name: "Черниговская", value: 6 },
  { name: "Черновицкая", value: 25 },
];
